### PR TITLE
added Python interview question with solution - first round online assessment 

### PR DESCRIPTION
**Pull request by NirmalSilwal**
Hi @AjinkyaTaranekar, I have added one of the interview question along with solution that I recently gave for. The role was related to Python developer. I think sharing company name is inappropriate so haven't mentioned that.

You can find the proposed file screenshot below:

added project files

Do let me know of this PR.

Thanks

### CODE REVIEW

**Comment by AjinkyaTaranekar** [comment]
Hello, can you change folder name it's okay if name couldn't be disclosed to something like Python Developer Role ~ (Startup/MNC/FAANG). Also mention question and output in a README.md for that folder instead of a .docx or .txt file.

Share your suggestions also.

**Comment by NirmalSilwal** [comment]
sounds good. Let me add readme for it and change folder name.
Thanks for the suggestion.

**Comment by NirmalSilwal** [comment]
Hi @AjinkyaTaranekar, I am confused, as I made all changes - added readme files of question and sample input from browser itself. Didn't get idea to pull the changes made in another branch **AddinterviewQuestion** to my local system. 

In this case do I need to create another pull request or is there a way to make pull request from these changes itself, as I added readme from github browser in another branch **AddinterviewQuestion** to my local system.

Any suggestions?

**Comment by NirmalSilwal** [comment]
Though file changes are reflected here itself, I was wondering if I could change the folder name also, rest of is all set to merge. Do let me know if you have suggestions.

Thanks

**Comment by NirmalSilwal** [comment]
Hi @AjinkyaTaranekar, Any update on this PR?

**Pull request merged**
